# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cedcb4140af6b7f9706915b08a0972ec4d1e2f725b34348ec1d33bbd889ce816e9beeef6b529d10d1f06985559341aa31d0d27250b144b0cc1473529123f29d

test:
  secret_key_base: a9c2d3dff5f875bfdb4be577f5172332be8fc30173227aad88c9bbb02db3a50e4985772d7aa332dfb2537a0e3365cf476469f8b54a7e06af9c9d3bfcdce005f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
